<?php if(!defined('BASEPATH'))exit('No direct script access allowed');class Api extends CI_Controller{public function __construct(){parent::__construct();header('Content-type: text/json');date_default_timezone_set('Asia/Kolkata');$this->load->database();$this->load->model('api_model');$this->load->library('form_validation');$this->load->helper(array('form','url'));$this->db->query("SET time_zone='+05:30'");$this->load->library('email');}
function claims_job_locatioon(){$this->form_validation->set_rules("aid","aid","required");$this->form_validation->set_rules("location","location","required");$this->form_validation->set_rules("latitude","latitude","required");$this->form_validation->set_rules("latitude","latitude","required");$this->load->library('form_validation');$array=array();if($this->form_validation->run()==FALSE){$data=array('success'=>false,'message'=>'All Fields Required','data'=>[]);}
else{$curr_date=date("Y-m-d H:i:s");$aid=$this->input->post('aid');$edr="Select * from `claims_job`";$q2=$this->db->query($edr);$realiddd='';foreach($q2->result()as $open){$countt=$open->id;if(password_verify($countt,$aid)){$realiddd=$countt;}}
$edr="Select * from `claims_job` where id='".$realiddd."' and location is null";$q=$this->db->query($edr);if($q->num_rows()>0){$setpin=array('location'=>($this->input->post('location')),'latitude'=>($this->input->post('latitude')),'longitude'=>($this->input->post('longitude')));$responseee=$this->api_model->update_case_details($setpin,$realiddd);if($responseee=='1'){$data=array('success'=>true,'message'=>'Successfully Update','data'=>[]);}
else{$data=array('success'=>false,'message'=>'Error or already Update location','data'=>[]);}}
else{$data=array('success'=>false,'message'=>'Invalid AID','data'=>[]);}}
echo json_encode($data,true);}
function upload_case_file(){$this->form_validation->set_rules("inspector_id","inspector_id","required");$this->form_validation->set_rules("aid","aid","required");$inspector_id=$this->input->post('inspector_id');$aid=$this->input->post('aid');$this->load->library('form_validation');$array=array();if($this->form_validation->run()==FALSE){$data=array('success'=>false,'message'=>'All Fields Required',);$data['data']=[];}
else{$addre="Select * from `claims_users` where  id='".$inspector_id."' and app_user='1'";$q2=$this->db->query($addre);if($q2->num_rows()==0){$data=array('success'=>false,'message'=>'Invalid Inspector ID',);$data['data']=[];}
else{$selficheck="Select * from `claims_job` where aid='".$aid."'";$checkuploadation=$this->db->query($selficheck);if($checkuploadation->num_rows()==0){$data=array('success'=>false,'message'=>'Invalid Case Id',);}
else{$file_type=$this->input->post('file_type');if($file_type=='image'){$new_name=time().$_FILES["file"]['name'];$config['file_name']=$new_name;$config['upload_path']='./uploads/case_image_files/';$config['allowed_types']='jpg|png|jpeg';$data2=[];$this->load->library('upload',$config);$this->upload->initialize($config);if(!$this->upload->do_upload("file")){$eeror=$this->upload->display_errors();$data=array('success'=>false,'message'=>$eeror,);}else{$file_namee=$this->upload->data('file_name');$curr_date=date("Y-m-d H:i:s");$upload_selfie=array('case_aid'=>$aid,'inspector_id'=>$inspector_id,'file_type'=>'image','file_name'=>'uploads/case_image_files/'.$file_namee,'created_at'=>$curr_date,);$responsecasefile=$this->api_model->insert_case_files($upload_selfie,$aid);if($responsecasefile=='1'){$data=array('success'=>True,'message'=>'Upload Image File Successfully',);}
else{$data=array('success'=>false,'message'=>'Error',);}}}
else if($file_type=='video'){$new_name=time().$_FILES["file"]['name'];$config['file_name']=$new_name;$config['upload_path']='./uploads/case_video_files/';$config['allowed_types']='mp4|wmv';$data2=[];$this->load->library('upload',$config);$this->upload->initialize($config);if(!$this->upload->do_upload("file")){$eeror=$this->upload->display_errors();$data=array('success'=>false,'message'=>$eeror,);}else{$file_namee=$this->upload->data('file_name');$curr_date=date("Y-m-d H:i:s");$upload_selfie=array('case_aid'=>$aid,'inspector_id'=>$inspector_id,'file_type'=>'video','file_name'=>'uploads/case_video_files/'.$file_namee,'created_at'=>$curr_date,);$responsecasefile=$this->api_model->insert_case_files($upload_selfie,$aid);if($responsecasefile=='1'){$data=array('success'=>True,'message'=>'Upload Video File Successfully',);}
else{$data=array('success'=>false,'message'=>'Error',);}}}
else if($file_type=='others'){$new_name=time().$_FILES["file"]['name'];$config['file_name']=$new_name;$config['upload_path']='./uploads/case_other_files/';$config['allowed_types']='pdf';$data2=[];$this->load->library('upload',$config);$this->upload->initialize($config);if(!$this->upload->do_upload("file")){$eeror=$this->upload->display_errors();$data=array('success'=>false,'message'=>$eeror,);}else{$file_namee=$this->upload->data('file_name');$curr_date=date("Y-m-d H:i:s");$upload_selfie=array('case_aid'=>$aid,'inspector_id'=>$inspector_id,'file_type'=>'pdf','file_name'=>'uploads/case_other_files/'.$file_namee,'created_at'=>$curr_date,);$responsecasefile=$this->api_model->insert_case_files($upload_selfie,$aid);if($responsecasefile=='1'){$data=array('success'=>True,'message'=>'Upload PDF File Successfully',);}
else{$data=array('success'=>false,'message'=>'Error',);}}}
else{$data=array('success'=>false,'message'=>'Invalid File Type',);}}}}
echo json_encode($data,true);}
function get_cases_details(){$this->form_validation->set_rules("aid","aid","required");$aid=$this->input->post('aid');$this->load->library('form_validation');$array=array();if($this->form_validation->run()==FALSE){$data=array('success'=>false,'message'=>'All Fields Required',);$data['data']=[];}
else{$valid_case="Select * from `claims_job` where aid='".$aid."'";$checkvalid_case=$this->db->query($valid_case);if($checkvalid_case->num_rows()>0){$data=array('success'=>true,'message'=>'Case Details',);$data['data']=$this->api_model->get_Case_details($aid);}
else{$data=array('success'=>false,'message'=>'Invalid Case Id');}}
echo json_encode($data,true);}
function asign_case(){$this->form_validation->set_rules("inspector_id","inspector_id","required");$this->form_validation->set_rules("aid","aid","required");$inspector_id=$this->input->post('inspector_id');$aid=$this->input->post('aid');$this->load->library('form_validation');$array=array();if($this->form_validation->run()==FALSE){$data=array('success'=>false,'message'=>'All Fields Required',);$data['data']=[];}
else{$valid_insp="Select * from `claims_users` where id='".$inspector_id."' and  app_user='1'";$chekvalidinsp=$this->db->query($valid_insp);if($chekvalidinsp->num_rows()>0){$valid_case="Select * from `claims_job` where aid='".$aid."'";$checkcasevalid=$this->db->query($valid_case);if($checkcasevalid->num_rows()>0){$case_asigncheck="SELECT t.*,t.id as case_idd FROM claims_job t LEFT JOIN claims_job_assign tl ON tl.aid = t.aid WHERE  t.aid='".$aid."' and  t.location!='' and tl.aid IS NULL";$case_asign_check=$this->db->query($case_asigncheck);if($case_asign_check->num_rows()>0){foreach($case_asign_check->result()as $open){$real_case_id=$open->case_idd;}
$curr_date=date("Y-m-d H:i:s");$asign_case=array('aid'=>$aid,'uid_to'=>$inspector_id,'date_time'=>$curr_date);$respone_asigncase=$this->api_model->asign_Case($asign_case);$update_casestatus=array('status'=>'1');$responseee=$this->api_model->update_case_details($update_casestatus,$real_case_id);if($responseee=='1'){$data=array('success'=>true,'message'=>'Successfully Asign Case','data'=>[]);}
else{$data=array('success'=>false,'message'=>'Error','data'=>[]);}}
else{$data=array('success'=>false,'message'=>'Case Already Asign..',);}}
else{$data=array('success'=>false,'message'=>'Invalid Case Id');}}
else{$data=array('success'=>false,'message'=>'Invalid Inspector Id');}}
echo json_encode($data,true);}}?>