#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SQL_DUMP="${ROOT_DIR}/localhost.sql"
DB_NAME="adwiti_claimsmitra_db"
DB_USER="adwiti_claimsmitra_db"
SOCKET="/run/mysqld/mysqld.sock"
ENV_FILE="${ROOT_DIR}/.cursor/db.env"

# The DB password never gets hardcoded or committed. Reuse a password already
# exported into this shell (DB_PASSWORD); otherwise reuse one generated by a
# prior run of this script (${ENV_FILE}, gitignored); otherwise generate a
# fresh random one and persist it there for later runs and for the app server.
if [[ -n "${DB_PASSWORD:-}" ]]; then
  DB_PASS="${DB_PASSWORD}"
elif [[ -f "${ENV_FILE}" ]]; then
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  DB_PASS="${DB_PASSWORD:?DB_PASSWORD missing from ${ENV_FILE}}"
else
  DB_PASS="$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 24)"
fi

mkdir -p "$(dirname "${ENV_FILE}")"
umask 077
cat > "${ENV_FILE}" <<EOF
export DB_HOSTNAME=127.0.0.1
export DB_USERNAME=${DB_USER}
export DB_PASSWORD=${DB_PASS}
export DB_DATABASE=${DB_NAME}
EOF

ensure_mysql_socket() {
  sudo mkdir -p /run/mysqld /var/run/mysqld
  sudo chown mysql:mysql /run/mysqld /var/run/mysqld
  if [[ -S "${SOCKET}" && ! -e /var/run/mysqld/mysqld.sock ]]; then
    sudo ln -sf "${SOCKET}" /var/run/mysqld/mysqld.sock
  fi
}

ensure_mysql_socket

mysql_admin() {
  if mysqladmin ping --socket="${SOCKET}" --silent 2>/dev/null; then
    sudo mysql --socket="${SOCKET}" "$@"
  else
    sudo mysql "$@"
  fi
}

mysql_client() {
  mysql --socket="${SOCKET}" -u "${DB_USER}" -p"${DB_PASS}" "$@"
}

echo "Ensuring MariaDB is running..."
if ! mysqladmin ping --socket="${SOCKET}" --silent 2>/dev/null; then
  sudo mkdir -p /run/mysqld
  sudo chown mysql:mysql /run/mysqld
  if ! pgrep -x mariadbd >/dev/null 2>&1; then
    sudo mysqld_safe \
      --datadir=/var/lib/mysql \
      --socket="${SOCKET}" \
      --pid-file=/run/mysqld/mysqld.pid \
      >/tmp/claimsmitra-mysqld.log 2>&1 &
  fi
fi

for _ in $(seq 1 60); do
  if mysqladmin ping --socket="${SOCKET}" --silent 2>/dev/null; then
    break
  fi
  sleep 1
done

if ! mysqladmin ping --socket="${SOCKET}" --silent 2>/dev/null; then
  echo "MariaDB did not become ready." >&2
  exit 1
fi

mysql_admin -e "
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
"

TABLE_COUNT="$(mysql_admin -N -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${DB_NAME}';")"
if [[ "${TABLE_COUNT}" == "0" ]]; then
  echo "Importing ${SQL_DUMP}..."
  mysql_admin "${DB_NAME}" < "${SQL_DUMP}"
else
  echo "Database ${DB_NAME} already initialized (${TABLE_COUNT} tables)."
fi

USER_COUNT="$(mysql_client "${DB_NAME}" -N -e "SELECT COUNT(*) FROM claims_users;" 2>/dev/null || echo 0)"
echo "Database ready with ${USER_COUNT} users."
echo "DB credentials written to ${ENV_FILE} (gitignored); sourced automatically by start.sh and the web terminal."
